sudo: required

language: bash

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - docker build -t inaetics/buildroot_minimum_celix buildroot_minimum_celix && docker push inaetics/buildroot_minimum_celix
  - docker build -t inaetics/cagent_builder cagent_builder && docker push inaetics/cagent_builder
