#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbJm/ibLjMdkRwcLwfj1cbq2mb9dJHPRPEsQn/vgaEnxDOIUF3YXgntu7+L6NHofMw3nFwkd6wsmo8R7Ho4o9j/MQSagf42hDneLvCXBsPwD+kYORPkWHs54gZYLyrvx3VeDNr/qpC+nOLH83NWkgpSvqL3McmqzZetjE0A0nuUG4983rPEl7L0e1k6AOK9kHFQ1QGfZAspWE5i09iRfaNVTXOsYoMzsfj94xj5kk6a7apwF5MB5UJJqCuWzqieilXE+sp8dKlMNRlTrYsmRdpdooxgSIqiP8jm4dls0qqosGY6i+q43uMVH6fvfYldksRgDQpYFH/tIO4S595oCC5 maintain@INAETICS-Gerrit.lan

write_files:
  - path: /opt/bin/setup-env.sh
    content: |
        #/bin/sh
        env=/etc/environment
        function get_ipv4() {
            IP=
            while [ 1 ]; do
                IP=$(ip -f inet addr show | grep 'state UP' -A2 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)
            if [ "$IP" != "" ]; then
                break
            fi
            sleep .1
            done
            echo $IP
        }
        # setup environment file
        if [ -f "${env}" ]; then
            sed -i -e '/^COREOS_PUBLIC_IPV4=/d' -e '/^COREOS_PRIVATE_IPV4=/d' -e '/^COREOS_PUBLIC_IPV6=/d' -e '/^COREOS_PRIVATE_IPV6=/d' "${env}"
        fi
        ipv4=$(get_ipv4)
        echo "COREOS_PUBLIC_IPV4=${ipv4}" >> ${env}
        echo "COREOS_PRIVATE_IPV4=${ipv4}" >> ${env}
        # not adding the IPV6 addresses, as we're not using a IPV6 setup...
        # For now, only start workers
        touch /tmp/worker

coreos:
    units:
        - name: setup-environment.service
          command: start
          runtime: true
          content: |
            [Unit]
            Description=Setup environment with public/private IP addresses
 
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/bin/sh /opt/bin/setup-env.sh
        - name: oem-master-cloudinit.service
          command: restart
          runtime: true
          content: |
            [Unit]
            Description=Call cloud-init for 2nd-stage user-data
            After=setup-environment.service
            ConditionPathExists=/tmp/master
 
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            EnvironmentFile=/etc/environment
            ExecStartPre=/usr/bin/mount -o remount,size=3G,noatime / 
            ExecStart=/usr/bin/coreos-cloudinit --from-url=http://172.168.1.180/cloud-config-master-stage2.yml
        - name: oem-worker-cloudinit.service
          command: restart
          runtime: true
          content: |
            [Unit]
            Description=Call cloud-init for 2nd-stage user-data
            After=setup-environment.service
            ConditionPathExists=/tmp/worker
 
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            EnvironmentFile=/etc/environment
            ExecStartPre=/usr/bin/mount -o remount,size=3G,noatime / 
            ExecStart=/usr/bin/coreos-cloudinit --from-url=http://172.168.1.180/cloud-config-worker-stage2.yml

